spring:
  security:
    user:
      name: root
      password: 1234

  datasource:
    username: root
    password: 1234
    url: jdbc:mysql://localhost:3306/security
  jpa:
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update

